In [ ]:
# if running this is something like google colab first uncomment and run below to install latest version of netdata-pandas
#!pip install --upgrade netdata-pandas

In [ ]:
from netdata_pandas.data import get_data

Lets pull some data from our two demo servers into a pandas dataframe.

In [ ]:
hosts = ['london.my-netdata.io', 'newyork.my-netdata.io']
charts = ['system.cpu', 'system.load']
after = -60
before = 0

df = get_data(hosts, charts, after, before)
print(df.shape)
df.head()

(120, 24)

                                 system.cpu|guest_nice  system.cpu|guest  \
host                 time_idx
london.my-netdata.io 1592303468                    0.0               0.0
                     1592303469                    0.0               0.0
                     1592303470                    0.0               0.0
                     1592303471                    0.0               0.0
                     1592303472                    0.0               0.0

                                 system.cpu|steal  system.cpu|softirq  \
host                 time_idx
london.my-netdata.io 1592303468               0.0            0.000000
                     1592303469               0.0            0.252525
                     1592303470               0.0            0.000000
                     1592303471               0.0            0.000000
                     1592303472               0.0            0.000000

                                 system.cpu|irq  system.cpu|user  \
host                 time_idx
london.my-netdata.io 1592303468             0.0         0.502513
                     1592303469             0.0         0.252525
                     1592303470             0.0         0.751880
                     1592303471             0.0         0.502513
                     1592303472             0.0         0.503778

                                 system.cpu|system  system.cpu|nice  \
host                 time_idx
london.my-netdata.io 1592303468           0.753769              0.0
                     1592303469           0.252525              0.0
                     1592303470           0.751880              0.0
                     1592303471           0.502513              0.0
                     1592303472           0.755668              0.0

                                 system.cpu|iowait  system.load|load1  ...  \
host                 time_idx                                          ...
london.my-netdata.io 1592303468                0.0                NaN  ...
                     1592303469                0.0                NaN  ...
                     1592303470                0.0                NaN  ...
                     1592303471                0.0                NaN  ...
                     1592303472                0.0                NaN  ...

                                 system.cpu|steal  system.cpu|softirq  \
host                 time_idx
london.my-netdata.io 1592303468               NaN                 NaN
                     1592303469               NaN                 NaN
                     1592303470               NaN                 NaN
                     1592303471               NaN                 NaN
                     1592303472               NaN                 NaN

                                 system.cpu|irq  system.cpu|user  \
host                 time_idx
london.my-netdata.io 1592303468             NaN              NaN
                     1592303469             NaN              NaN
                     1592303470             NaN              NaN
                     1592303471             NaN              NaN
                     1592303472             NaN              NaN

                                 system.cpu|system  system.cpu|nice  \
host                 time_idx
london.my-netdata.io 1592303468                NaN              NaN
                     1592303469                NaN              NaN
                     1592303470                NaN              NaN
                     1592303471                NaN              NaN
                     1592303472                NaN              NaN

                                 system.cpu|iowait  system.load|load1  \
host                 time_idx
london.my-netdata.io 1592303468                NaN                NaN
                     1592303469                NaN                NaN
                     1592303470                NaN               0.03
                     1592303471                NaN               0.03
                     1592303472                NaN               0.03

                                 system.load|load5  system.load|load15
host                 time_idx
london.my-netdata.io 1592303468                NaN                 NaN
                     1592303469                NaN                 NaN
                     1592303470               0.02                0.01
                     1592303471               0.02                0.01
                     1592303472               0.02                0.01

[5 rows x 24 columns]

Lets have a look at some timings in pulling this data.

In [ ]:
%%timeit

df = get_data(hosts, charts, after, before)

215 ms Â± 26.5 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

If we wanted to pull data for all charts we can do something like this.

In [ ]:
df = get_data('london.my-netdata.io', 'all', after, before)
print(df.shape)
df.head()

(66, 2091)

,disk_qops.vda|operations,groups.pipes|ulog,groups.pipes|messagebus,groups.pipes|unscd,groups.pipes|bind,groups.pipes|nogroup,groups.pipes|ntp,groups.pipes|postfix,groups.pipes|mysql,groups.pipes|www-data,...,apps.major_faults|containers,apps.major_faults|ssh,apps.major_faults|time,apps.major_faults|named,apps.major_faults|cron,apps.major_faults|ksmd,apps.major_faults|system,apps.major_faults|kernel,apps.major_faults|other,apps.major_faults|build
time_idx,,,,,,,,,,,,,,,,,,,,,
1592303570,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1592303571,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1592303572,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1592303573,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1592303574,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [ ]:
df.describe()

,disk_qops.vda|operations,groups.pipes|ulog,groups.pipes|messagebus,groups.pipes|unscd,groups.pipes|bind,groups.pipes|nogroup,groups.pipes|ntp,groups.pipes|postfix,groups.pipes|mysql,groups.pipes|www-data,...,apps.major_faults|logs,apps.major_faults|containers,apps.major_faults|ssh,apps.major_faults|time,apps.major_faults|named,apps.major_faults|cron,apps.major_faults|ksmd,apps.major_faults|system,apps.major_faults|kernel,apps.major_faults|other
count,66.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,...,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0,60.0
mean,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0